# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  #schedule:
    #- cron: '0 22 * * *'
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python files
      run: |
        python run_all.py
    - name: Check failures
      id: CF
      run: |
        py_nums=$(ls -l ./CUC_Report|grep "py$"|wc -l) &&
        suc_nums=$(grep -o '"check_code":0' ./CUC_Report/log.txt | wc -l) &&
        fail_num=$[py_nums - suc_nums] &&
        if [ $fail_num -eq 0 ];then CUC_JOB_STATUS='[Success]';else CUC_JOB_STATUS='Number of [Failures]: '$fail_num;fi &&
        echo $CUC_JOB_STATUS &&
        echo "::set-output name=CUC_JOB_STATUS::$CUC_JOB_STATUS"
    - name: Send mail
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: ${{ steps.CF.outputs.CUC_JOB_STATUS }} epidemic reports of CUC.
        body: file://CUC_Report/log.txt
        to: xxx@xxxxx.xxx
        from: GitHub Actions
